create table if not exists employee
(
    id         bigint generated by default as identity
        primary key,
    birth_date timestamp(6),
    login      varchar(255),
    name       varchar(255),
    password   varchar(255),
    surname    varchar(255)
);

alter table employee
    owner to postgres;

create table if not exists projects
(
    id                  bigint generated by default as identity
        primary key,
    code                varchar(255),
    date_of_start       date,
    description         varchar(255),
    fact_date_of_end    date,
    fact_payload        bigint,
    name                varchar(255),
    planned_date_of_end date,
    planned_payload     bigint,
    responsible_login   varchar(255),
    status              varchar(255)
        constraint projects_status_check
            check ((status)::text = ANY ((ARRAY ['IN_PROGRESS'::character varying, 'END'::character varying])::text[])),
    type                varchar(255)
        constraint projects_type_check
            check ((type)::text = ANY
                   ((ARRAY ['BUSINESS'::character varying, 'TECHNICAL'::character varying, 'RESEARCH'::character varying])::text[]))
);

alter table projects
    owner to postgres;

create table if not exists task
(
    id              bigint generated by default as identity
        primary key,
    description     varchar(255),
    fact_payload    double precision,
    number          varchar(255),
    planned_payload double precision,
    project_id      bigint
        constraint fk59mygkh6yxl8yj6j8ocg1k73a
            references projects
);

alter table task
    owner to postgres;




-- Вставка сотрудников
INSERT INTO employee (birth_date, login, name, password, surname) VALUES
                                                                      ('1990-05-15 00:00:00', 'ivanov', 'Иван', 'pass1', 'Иванов'),
                                                                      ('1985-08-22 00:00:00', 'petrova', 'Мария', 'pass2', 'Петрова'),
                                                                      ('1992-03-10 00:00:00', 'smirnov', 'Алексей', 'pass3', 'Смирнов'),
                                                                      ('1988-11-30 00:00:00', 'sidorova', 'Ольга', 'pass4', 'Сидорова'),
                                                                      ('1995-07-19 00:00:00', 'kuznetsov', 'Дмитрий', 'pass5', 'Кузнецов'),
                                                                      ('1991-09-25 00:00:00', 'vorobyova', 'Анна', 'pass6', 'Воробьёва');

-- Вставка проектов
INSERT INTO projects (code, date_of_start, description, fact_date_of_end, fact_payload, name,
                      planned_date_of_end, planned_payload, responsible_login, status, type) VALUES
                                                                                                 ('ALP', '2023-01-01', 'Бизнес-платформа', NULL, NULL, 'Alpha',
                                                                                                  '2023-06-30', 1000, 'petrova', 'IN_PROGRESS', 'BUSINESS'),

                                                                                                 ('BET', '2022-05-10', 'Техническая инфраструктура', '2023-01-20', 850, 'Beta',
                                                                                                  '2022-12-15', 800, 'ivanov', 'END', 'TECHNICAL'),

                                                                                                 ('GAM', '2023-03-15', 'Научные исследования', NULL, NULL, 'Gamma',
                                                                                                  '2023-09-30', 1200, 'sidorova', 'IN_PROGRESS', 'RESEARCH'),

                                                                                                 ('DEL', '2021-07-01', 'Корпоративная система', '2022-04-20', 1450, 'Delta',
                                                                                                  '2022-05-01', 1500, 'kuznetsov', 'END', 'BUSINESS'),

                                                                                                 ('EPS', '2023-04-01', 'API-интеграции', NULL, NULL, 'Epsilon',
                                                                                                  '2023-08-31', 900, 'vorobyova', 'IN_PROGRESS', 'TECHNICAL'),

                                                                                                 ('ZET', '2020-09-01', 'Фундаментальные исследования', '2021-02-15', 1950, 'Zeta',
                                                                                                  '2021-03-01', 2000, 'smirnov', 'END', 'RESEARCH');

-- Вставка задач
INSERT INTO task (description, fact_payload, number, planned_payload, project_id) VALUES
                                                                                      ('Разработка архитектуры', 180, 'ALP-001', 200, 1),
                                                                                      ('Тестирование', 160, 'ALP-002', 150, 1),
                                                                                      ('Реализация модуля', 320, 'BET-001', 300, 2),
                                                                                      ('Документация', 200, 'BET-002', 200, 2),
                                                                                      ('Исследование рынка', NULL, 'GAM-001', 400, 3),
                                                                                      ('Анализ данных', NULL, 'GAM-002', 350, 3),
                                                                                      ('Внедрение системы', 680, 'DEL-001', 700, 4),
                                                                                      ('Обучение сотрудников', 500, 'DEL-002', 500, 4),
                                                                                      ('Разработка API', NULL, 'EPS-001', 300, 5),
                                                                                      ('Интеграция', NULL, 'EPS-002', 250, 5),
                                                                                      ('Лабораторные тесты', 950, 'ZET-001', 1000, 6),
                                                                                      ('Анализ результатов', 800, 'ZET-002', 800, 6);


-- Функция для расчёта суммарной нагрузки проекта по задачам
CREATE OR REPLACE FUNCTION calculate_project_payload(project_code varchar)
    RETURNS numeric AS $$
DECLARE
    total_payload numeric;
BEGIN
    SELECT COALESCE(SUM(t.fact_payload), 0)
    INTO total_payload
    FROM task t
             JOIN projects p ON t.project_id = p.id
    WHERE p.code = project_code;

    RETURN total_payload;
END;
$$ LANGUAGE plpgsql;

-- Процедура для увеличения нагрузки задач на 20%
CREATE OR REPLACE PROCEDURE increase_tasks_payload()
    LANGUAGE plpgsql AS $$
BEGIN
    UPDATE task
    SET fact_payload = fact_payload * 1.20
    WHERE fact_payload IS NOT NULL;

    COMMIT;
END;
$$;