------------------------- сотрудник
create table employee
(
    id        bigserial
        constraint employee_pk
            primary key,
    login     varchar(36) not null,
    password  varchar(255),
    name      varchar(36) not null,
    surname   varchar(36) not null,
    birthdate date
);

alter table employee
    owner to postgres;

create unique index employee_id_uindex
    on employee (id);

create unique index employee_login_uindex
    on employee (login);

INSERT INTO employee(login, name, surname)
VALUES
    ('ale.v.timofeev', 'Тимофеев Алексей Владимирович', 'timofeev@example.com'),
    ('k.timofeeva', 'Петров Петр Петрович', 'timofeeva@example.com');


------------------------- проекты

create table projects
(
    id                  bigint generated by default as identity
        primary key,
    code                varchar(255),
    date_of_start       date,
    description         varchar(255),
    fact_date_of_end    date,
    name                varchar(255),
    planned_date_of_end date,
    planned_payload     bigint,
    responsible_login   varchar(255)
        constraint fk_project_users
            references employee (login)
            on delete set null,
    status              smallint
        constraint projects_status_check
            check ((status >= 0) AND (status <= 1)),
    type                smallint
        constraint projects_type_check
            check ((type >= 0) AND (type <= 2))
);

INSERT INTO projects (code, name, description, date_of_start, fact_date_of_end, planned_date_of_end, status, type, planned_payload, responsible_login)
VALUES
    ('PRJ001', 'Business Development', 'Проект по развитию бизнеса', '2023-01-01', NULL, '2023-12-31', 'IN_PROGRESS', 'BUSINESS', 1000, 'ale.v.timofeev'),
    ('PRJ002', 'Technical Upgrade', 'Модернизация технической инфраструктуры', '2023-02-15', NULL, '2023-11-30', 'IN_PROGRESS', 'TECHNICAL', 1500, 'k.timofeeva'),
    ('PRJ003', 'Research Project', 'Исследовательский проект', '2023-03-01', '2023-09-30', '2023-10-15', 'END', 'RESEARCH', 800, 'ale.v.timofeev');
